"version": 1
"applications":
  "postgres-volume-example2":
    "image": "postgres:9.4"
    "ports":
    - "internal": 5432
      "external": 5433
    "volume":
      # The location within the container where the data volume will be
      # mounted; see https://github.com/docker-library/postgres/blob/docker/Dockerfile.template
      "mountpoint": "/var/lib/postgresql/data"
